name : Mi primer github action

on: 
  push: 
    branches: ["main"]

jobs:
  saludo:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: echo "Hola, este es mi primer mensaje"
      - name: Fallo intencionado
        run: exi 1
